[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "DENV_transmission_model"
version = "26.0.0"
description = "A dengue transmission model."
authors = [{name = "Dr. Tijs W. Alleman", email = "twa27@cornell.edu"}]
license = "CC-BY-NC-SA-4.0"
license-files = ["LICENSE-CC-BY-NC-SA.txt"]
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "jax",
    "jaxlib",
    "numpyro==0.21.0",
    "diffrax==0.7.2",
    "numpy",
    "pandas",
    "arviz>1.0",
    "netcdf4",
    "optax",
]

[project.optional-dependencies]
develop = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "tests.*"]
